### ISSUE TITLE
Strange warnings during Magento 2.4.0 installation

### ISSUE THREAD

**Issue by hostep** [magento/composer-root-update-plugin#15] opened 2020-07-28 20:22 UTC
Hi!

When setting up a clean Magento 2.4.0 installation using composer followed up by `bin/magento setup:install ...`, I'm getting the following output which seems to be caused by this module.

```
...
[Progress: 653 / 1207]
Module 'Magento_CmsUrlRewriteGraphQl':
[Progress: 654 / 1207]
Module 'Magento_ComposerRootUpdatePlugin':
Installing data... Reading /project-root/composer.json
Loading config file /project-root/composer.json
Loading config file /project-root/auth.json
Reading /project-root/auth.json
Failed to initialize global composer: Composer could not find the config file: /project-root/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /project-root/vendor/composer/installed.json
Reading /project-root/composer.lock
Checking for "magento/composer-root-update-plugin: 1.0.0" for the Web Setup Wizard...
Reading /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
Loading config file /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
No Web Setup Wizard update needed for magento/composer-root-update-plugin; version 1.0.0 is already in /project-root/var.
Upgrading data... Reading /project-root/composer.json
Loading config file /project-root/composer.json
Loading config file /project-root/auth.json
Reading /project-root/auth.json
Failed to initialize global composer: Composer could not find the config file: /project-root/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /project-root/vendor/composer/installed.json
Reading /project-root/composer.lock
Checking for "magento/composer-root-update-plugin: 1.0.0" for the Web Setup Wizard...
Reading /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
Loading config file /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
No Web Setup Wizard update needed for magento/composer-root-update-plugin; version 1.0.0 is already in /project-root/var.

[Progress: 655 / 1207]
Module 'Magento_User':
...
[Progress: 951 / 1207]
Module 'Magento_CmsUrlRewriteGraphQl':
[Progress: 952 / 1207]
Module 'Magento_ComposerRootUpdatePlugin':
Running data recurring...Reading /project-root/composer.json
Loading config file /project-root/composer.json
Loading config file /project-root/auth.json
Reading /project-root/auth.json
Failed to initialize global composer: Composer could not find the config file: /project-root/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /project-root/vendor/composer/installed.json
Reading /project-root/composer.lock
Checking for "magento/composer-root-update-plugin: 1.0.0" for the Web Setup Wizard...
Reading /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
Loading config file /project-root/var/vendor/magento/composer-root-update-plugin/composer.json
No Web Setup Wizard update needed for magento/composer-root-update-plugin; version 1.0.0 is already in /project-root/var.

[Progress: 953 / 1207]
Module 'Magento_User':
...
```

Is this expected? Seems like a lot of noise.

What's the deal with this warning?
```
Failed to initialize global composer: Composer could not find the config file: /project-root/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

**Comment by ioweb-gr** [comment] 2020-07-31 08:45
Apparently if you create an empty file in var/composer_home/composer.json with `{}` as content it will proceed but you get the other warnings as well. There's something weird going on

**Comment by hostep** [comment] 2020-07-31 10:22
@pdohogne-magento: do you have some explanation for this? Thanks!

**Comment by m-v-v** [comment] 2020-08-03 12:10
Got the same problem when doing a fresh install of Magento 2.4.0

**Comment by kamzata** [comment] 2020-08-04 00:51
Same issue here with a fresh install of Magento 2.4.0 therefore I can't install Magento!

**Comment by hostep** [comment] 2020-08-04 07:04
@kamzata: what do you mean with you "can't install Magento"?
I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.

**Comment by m-v-v** [comment] 2020-08-04 07:25
@kamzata I also can install Magento 2.4.0 but missing the composer.json and auth.json file in var/composer_home folder after the install.
With a fresh install of Magento 2.3.5 these files are installed in the var/composer_home folder.

**Comment by kamzata** [comment] 2020-08-04 10:06
> @kamzata: what do you mean with you "can't install Magento"?
> I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.

It doesn't block the installation process, actually it says "Installation Success", but then when I try to open the website it shows a 500 Error. Did you make a fresh 2.4.0 installation?

**Comment by kamzata** [comment] 2020-08-04 10:08
> @kamzata I also can install Magento 2.4.0 but missing the composer.json and auth.json file in var/composer_home folder after the install.
> With a fresh install of Magento 2.3.5 these files are installed in the var/composer_home folder.

Were you able to install 2.4.0 with a fresh installation? Or did you upgrade from 2.3.5-p2?

**Comment by hostep** [comment] 2020-08-04 10:29
@kamzata: Both a fresh install of 2.4.0 and an upgrade from 2.3.5 to 2.4.0 works over here.
I'd advise you to search help for your issue elsewhere as your issue seems to have nothing to do with this ticket here, thanks! 🙂

**Comment by kamzata** [comment] 2020-08-04 12:17
> @kamzata: Both a fresh install of 2.4.0 and an upgrade from 2.3.5 to 2.4.0 works over here.
> I'd advise you to search help for your issue elsewhere as your issue seems to have nothing to do with this ticket here, thanks! 🙂

Might I ask you to show me your install command? Just worked the upgrade for me.

I receive the same errors for composer root update plugin while installing...

**Comment by pushpendra07** [comment] 2020-08-10 06:32
I have solved this issue by removing below module from composer file

"magento/composer-root-update-plugin": "~1.0",

**Comment by ioweb-gr** [comment] 2020-08-10 06:37
@pushpendra07 The whole point of this issue is that this composer module is throwing the warnings but it should not

**Comment by pushpendra07** [comment] 2020-08-10 06:40
> @pushpendra07 The whole point of this issue is that this composer module is throwing the warnings but it should not
@ioweb-gr
but after removing this module it's update my composer version to 1.10.10

**Comment by alex-campu** [comment] 2020-08-27 20:52
> > @kamzata: what do you mean with you "can't install Magento"?
> > I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.
> 
> It doesn't block the installation process, actually it says "Installation Success", but then when I try to open the website it shows a 500 Error. Did you make a fresh 2.4.0 installation?

It happened to me but with error 502. did you solve the issue?

**Comment by kamzata** [comment] 2020-08-28 00:00
> > > @kamzata: what do you mean with you "can't install Magento"?
> > > I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.
> > 
> > 
> > It doesn't block the installation process, actually it says "Installation Success", but then when I try to open the website it shows a 500 Error. Did you make a fresh 2.4.0 installation?
> 
> It happened to me but with error 502. did you solve the issue?

Yeah! It took me a while but I made it. Do you use a reverse proxy? [Take a look here](https://magento.stackexchange.com/a/319608/13970). Let me know if this helped!

**Comment by yesiyan01** [comment] 2020-10-28 04:52
Had the same warnings but installation is successful nevertheless. Received 502 error initially but turns out my nginx setup was the culprit as it was complaining about the size of the header, and increasing the proxy_buffer_size fixed the issue.

**Comment by driiftkiing** [comment] 2020-10-28 10:22
> > > > @kamzata: what do you mean with you "can't install Magento"?
> > > > I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.
> > > 
> > > 
> > > It doesn't block the installation process, actually it says "Installation Success", but then when I try to open the website it shows a 500 Error. Did you make a fresh 2.4.0 installation?
> > 
> > 
> > It happened to me but with error 502. did you solve the issue?
> 
> Yeah! It took me a while but I made it. Do you use a reverse proxy? [Take a look here](https://magento.stackexchange.com/a/319608/13970). Let me know if this helped!

Thanks, also worked for me with a reverse-proxy.

```
proxy_buffers              128 8k;
proxy_buffer_size          512k;
proxy_busy_buffers_size    512k;
```

**Comment by kamzata** [comment] 2020-10-28 14:08
> > > > > @kamzata: what do you mean with you "can't install Magento"?
> > > > > I have no problems setting up 2.4.0, this output is just debug/warning output, it doesn't seem to block the installation in my case.
> > > > 
> > > > 
> > > > It doesn't block the installation process, actually it says "Installation Success", but then when I try to open the website it shows a 500 Error. Did you make a fresh 2.4.0 installation?
> > > 
> > > 
> > > It happened to me but with error 502. did you solve the issue?
> > 
> > 
> > Yeah! It took me a while but I made it. Do you use a reverse proxy? [Take a look here](https://magento.stackexchange.com/a/319608/13970). Let me know if this helped!
> 
> Thanks, also worked for me with a reverse-proxy.
> 
> ```
> proxy_buffers              128 8k;
> proxy_buffer_size          512k;
> proxy_busy_buffers_size    512k;
> ```

Glad to hear that. If it helped, please, vote for my answer on magento.stackexchange.com.

**Comment by jp8085** [comment] 2020-11-13 17:22
You can fix composer root plugin issue after removing root plugin line from composer.json and then run composer update command.
We have fixed this issue using this document.

Please refer it.

https://itcruncher.blogspot.com/2020/11/composer-error-in-magento-2-4-1.html

**Comment by pdohogne-magento** [comment] 2020-12-21 18:06
Closing original issue (unnecessary verbosity) as not a bug; Magento `setup:install` runs operations in `--verbose` mode, which is causing the increased level of logging.

**Closed as completed** 2020-12-21 18:06 UTC
Labels: not a bug

**Comment by hostep** [comment] 2020-12-21 20:43
@pdohogne-magento: ok, but that doesn't explain why this plugin (or some code in magento itself) is searching the directory `var/composer_home/` for a `composer.json` file. That's a strange and unexpected directory. Why does that happen?

**Comment by robsch** [comment] 2021-01-08 11:57
> Failed to initialize global composer: Composer could not find the config file: /project-root/var/composer_home/composer.json

So is that a problem or not? I get this with each `setup:upgrade`. What is the final solution? Ignoring or what?

**Comment by hostep** [comment] 2021-01-08 14:02
@robsch: I don't think this is an error, just a warning which you can ignore.
But I'm still curious about why that `var/composer_home/composer.json` file is being considered. @pdohogne-magento: if you have little bit of time, would be nice to get some sort of reply?

**Comment by pdohogne-magento** [comment] 2021-01-08 18:37
Yes this warning can be ignored if you're upgrading using the command line (which you should be, as the Web Setup Wizard UI upgrade tool is deprecated).  The plugin needs to support the Web Setup Wizard until the last Magento version that includes it (2.3.x) is EOL, so those warnings are around for the time being.  For CLI upgrades, any warnings to do with the `var` directory can be ignored; it's only used by the Wizard.

Here's some information about what's happening and why:

When upgrading using the Web Setup Wizard, it does a test dry-run upgrade in the `var` directory to make sure everything's OK before running on the actual composer.json file.  Because of how composer plugins work, the plugin needs to be available in the directory before this dry-run is executed (it can't be installed in the same operation where it needs to be active).  There are two ways of doing this: installing the plugin globally and pre-installing the plugin in the directory where the composer commands will be run.  We wanted to avoid installing the plugin globally for a number of reasons, so instead we wrote the plugin to install itself in the `var` directory.  The problem with that is that the `var` directory can be emptied, which uninstalls the plugin.  In an effort to keep the plugin installed properly, we attached the `var` self-installation code to Magento module operations; when a `setup:install` or `setup:upgrade` operation is executed, the plugin will attempt to re-install itself in the `var` directory if it was removed.  This is the operation that would cause this warning, though I've not seen the exact text before.

I'm betting (though not positive) this specific warning has to do with your local composer configuration, as composer_home is the name of the "global" composer directory where default configs and plugins are dictated.  When you run a composer operation, it looks for a global composer.json first then applies the local composer.json file's plugins and scripts on top of that.  It's possible you don't have a global composer_home configured elsewhere or something similar, so composer is looking in the directory where the commands are being run (`var`) as a default and can't find it there.

This directory being missing is just a warning and should have no actual bearing on the plugin's functionality, even when using the Web Setup Wizard.  It just means that no global configs will be used because they weren't found; composer will just use what it finds in the local directory, which is this plugin and nothing else.

Once again, this warning (and anything the plugin does that has to do with the `var` directory) is essentially deprecated and can be safely ignored if you're running your upgrade using the CLI `composer require`, `composer update`, and `setup:upgrade` commands as recommended.  This code will be removed once Magento 2.3 is EOL and the Web Setup Wizard no longer needs to be supported by the plugin.

**Comment by aepod** [comment] 2021-01-12 22:35
This breaks ece-tools from installing Magento automatically in Magento Cloud Docker. I think it is because it is passing a non-0 exit code. 
`returned non zero exit status 116 `

This issue started with the introduction of this package. Pre-2.4 you could install using ece-tools in MCD very easily.
See https://gist.github.com/aepod/faadfeef63b7a457436f270a1071884e for more details on that process.

If you remove this package from composer before running the cloud-deploy command it will work as intended, and you can always add the package back. But ideally we would fix this to work with ece-tools. 

@shiftedreality Here is the ticket I referred you to.

**Comment by pdohogne-magento** [comment] 2021-01-14 21:51
@aepod Please open a new issue for this problem with any information you have (what step it failed on, logs, error messages, etc.).  As far as I know, the warnings discussed in this issue should not cause a change in exit code.

**Comment by raxithrai** [comment] 2021-09-25 08:24
> @kamzata I also can install Magento 2.4.0 but missing the composer.json and auth.json file in var/composer_home folder after the install.
> With a fresh install of Magento 2.3.5 these files are installed in the var/composer_home folder.

@m-v-v  which code should i paste inside composer.json and auth.json in var/composer_home...please send the code to  rakshithrai90@gmail.com.

Thanks

**Comment by lano-vargas** [comment] 2022-06-27 13:34
> https://github.com/magento/composer-root-update-plugin/issues/15#issuecomment-671186772

Is this the right solution for open source version?
